const $=id=>document.getElementById(id);let lastState=null;
const fmt=s=>{s=Math.max(0,Math.floor(s||0));return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`};
function applyTheme(s){const a=s?.settings?.accent||"#8b5cf6";document.documentElement.style.setProperty("--accent",a);$("accent").value=a;$("hex").value=a;$("theme").value=s?.settings?.theme||"dark";$("compact").checked=!!s?.settings?.compact;$("reduced").checked=!!s?.settings?.reducedMotion;}
function render(s){lastState=s;applyTheme(s);const native=!!s.nativeConnected,discord=!!s.discordConnected;$("dot").className=`dot ${native&&discord?"good":native?"warn":"bad"}`;$("statusText").textContent=native?(discord?"Ready • Discord connected":"Helper connected • Discord not ready"):(s.lastError||"Desktop helper missing");const d=s.current;if(d){$("anime").textContent=d.title||"Anime";$("episode").textContent=`Episode ${d.episode??"—"}${d.total?` / ${d.total}`:""}`;$("playback").textContent=d.state||"—";$("time").textContent=`${fmt(d.position)} / ${fmt(d.duration)}`;$("fill").style.width=d.duration?`${Math.min(100,d.position/d.duration*100)}%`:"0%";if(d.image){$("cover").src=d.image;$("cover").onerror=()=>chrome.runtime.sendMessage({type:"coverFailed",title:d.title,url:d.image});}}else{$("anime").textContent="Nothing detected";$("episode").textContent="—";$("playback").textContent="—";$("time").textContent="00:00 / 00:00";$("cover").removeAttribute("src");$("fill").style.width="0%";}$("diag").innerHTML=`Discord app: <b>Bundled ✓</b><br>Native helper: <b>${native?"Connected":"Disconnected"}</b><br>Helper version: <b>${s.hostVersion||"—"}</b><br>Discord RPC: <b>${discord?"Connected":"Not connected"}</b><br>AnimeKai: <b>${d?"Detected":"Not detected"}</b><br>Player: <b>${d?.duration?"Detected":"Waiting"}</b><br>Playback: <b>${d?.state||"—"}</b><br>RPC mode: <b>${s.rpcVariant||"—"}</b>${s.lastError?`<br>Error: <b>${s.lastError}</b>`:""}`;if(s.repair){const r=s.repair;$("repairState").textContent=r.ok?"Healthy ✓":"Needs attention";$("repairResult").textContent=(r.fixed?.length?`Fixed: ${r.fixed.join(", ")}`:(r.summary||"Health check complete"));}}
function get(){chrome.runtime.sendMessage({type:"getState"},r=>{if(r)render(r)})}
function saveAppearance(){const accent=/^#[0-9a-f]{6}$/i.test($("hex").value)?$("hex").value:$("accent").value;chrome.runtime.sendMessage({type:"setSettings",settings:{accent,theme:$("theme").value,compact:$("compact").checked,reducedMotion:$("reduced").checked}},get)}
function refresh(){const b=$("refresh");b.disabled=true;b.textContent="Refreshing…";chrome.runtime.sendMessage({type:"refresh"},()=>setTimeout(()=>{get();b.disabled=false;b.textContent="↻ Refresh";},900));}
$("accent").oninput=e=>{$("hex").value=e.target.value;saveAppearance()};$("hex").onchange=saveAppearance;$("theme").onchange=saveAppearance;$("compact").onchange=saveAppearance;$("reduced").onchange=saveAppearance;$("refresh").onclick=refresh;
$("health").onclick=()=>chrome.runtime.sendMessage({type:"health"},()=>setTimeout(get,500));$("repair").onclick=()=>{if(confirm("Repair AnimeKai RPC? Your themes and personal settings will be kept."))chrome.runtime.sendMessage({type:"repair"},()=>setTimeout(get,800))};$("test").onclick=()=>chrome.runtime.sendMessage({type:"test"},()=>setTimeout(get,500));$("clear").onclick=()=>chrome.runtime.sendMessage({type:"clear"},get);$("open").onclick=()=>chrome.tabs.create({url:"https://animekai.be/"});$("copy").onclick=()=>chrome.runtime.sendMessage({type:"copyDiagnostics"},async r=>{await navigator.clipboard.writeText(r?.text||"");$("copy").textContent="Copied ✓";setTimeout(()=>$("copy").textContent="Copy diagnostics",1200)});chrome.runtime.onMessage.addListener(m=>{if(m.type==="v6State")render(m.state)});get();setInterval(get,1500);
